services:
  api:
    image: fftracker-api
    ports:
      - "8000:8000"
    restart: always

  # web:
  #   build: ./ffreact
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./ffreact:/ffreact

  nginx:
    image: fftracker-nginx
    ports:
      - "80:80"
    depends_on: 
      - api


