# Define the services in our multi-container app
services:
  # api contains the Django API
  api:
    image: fftracker-api:$BUILD_ENV
    # Run the Django build dockerfile
    build: ./ffdjango
    # Expose port 8080
    ports:
      - "8080:8080"
    # Restart when killed (during redeployment etc.)
    restart: always
  # nginx contains the NGINX web server and the React build files
  nginx:
    image: fftracker-nginx:$BUILD_ENV
    # Build the React site and set up NGINX
    build:
      context: .
      dockerfile: ./webserver/dockerfile
      args:
        BUILD_FOR: $BUILD_FOR
    # Expose port 80
    ports:
      - "80:80"
    # Connect this service to the Django service in the Docker network
    links: 
      - api
    # Do not run this service if the Django API is not running
    depends_on:
      - api


