# Generated by Django 4.1.3 on 2025-01-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0026_remove_households_childrensnacks_timestamps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubscriptionhistory',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='PausedDates',
            fields=[
                ('pd_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('related_hh', models.ForeignKey(db_column='related_hh_id', on_delete=django.db.models.deletion.CASCADE, related_name='paused_dates', to='fftracker.households')),
            ],
            options={
                'db_table': 'paused_dates',
                'managed': True,
            },
        ),
    ]
