# Generated by Django 4.1.3 on 2025-02-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0027_alter_productsubscriptionhistory_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pauseddates',
            old_name='related_hh',
            new_name='relatedHHId',
        ),
    ]
