# Generated by Django 4.1.3 on 2025-02-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0028_rename_related_hh_pauseddates_relatedhhid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pauseddates',
            old_name='relatedHHId',
            new_name='related_hh',
        ),
    ]
