# Generated by Django 4.1.3 on 2025-02-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0029_alter_households_ebt_refill_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietaryRestrictions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("restriction_type", models.CharField(max_length=50)),
                ("servings", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dietary_restrictions",
                        to="fftracker.households",
                    ),
                ),
            ],
            options={
                "db_table": "dietary_restrictions",
                "managed": True,
            },
        ),
    ]
