# Generated by Django 4.1.3 on 2025-02-05 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0029_rename_relatedhhid_pauseddates_related_hh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pauseddates',
            name='related_hh',
            field=models.ForeignKey(db_column='related_hh_id', on_delete=django.db.models.deletion.CASCADE, related_name='hh_pauseddates', to='fftracker.households'),
        ),
    ]
