# Generated by Django 4.1.3 on 2025-02-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fftracker", "0030_dietaryrestrictions"),
    ]

    operations = [
        migrations.AddField(
            model_name="households",
            name="restriction_flag",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
