# Generated by Django 4.1.3 on 2025-02-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0030_alter_pauseddates_related_hh'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PausedDates',
        ),
    ]
