# Generated by Django 4.1.3 on 2025-02-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0031_dateentry_delete_pauseddates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateentry',
            name='pause_date',
        ),
        migrations.AddField(
            model_name='dateentry',
            name='pause_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dateentry',
            name='pause_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
