# Generated by Django 4.1.3 on 2025-02-05 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0032_remove_dateentry_pause_date_dateentry_pause_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PausedDates',
            fields=[
                ('paused_date_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('pause_start_date', models.DateField()),
                ('pause_end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('hh_id', models.ForeignKey(db_column='hh_id', on_delete=django.db.models.deletion.CASCADE, related_name='paused_dates', to='fftracker.households')),
            ],
            options={
                'db_table': 'paused_dates',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='DateEntry',
        ),
    ]
