# Generated by Django 4.1.3 on 2025-02-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0031_households_restriction_flag'),
        ('fftracker', '0033_pauseddates_delete_dateentry'),
    ]

    operations = [
    ]
