# Generated by Django 4.1.3 on 2025-02-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fftracker', '0034_merge_20250220_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_servings', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'servings',
                'managed': True,
            },
        ),
    ]
